module.exports = {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    theme: {
        extend: {
            fontFamily: {
                sans: ['JetBrains Mono', 'monospace'],
            },
        },
        screens: {
            sm: "640px",
            md: "768px",
            lg: "1024px",
            xl: "1280px",
        },
    },
    safelist: [
        "text-cyan-200",
        "hover:text-pink-300",
        "transition-colors",
        "text-lg",
        "hidden",
        "md:flex",
        "gap-6",
        "flex-wrap",
        "justify-center",
        "flex-1",
        "mx-8",
        "md:hidden",
        "text-3xl",
        "ml-auto",
        "flex",
        "flex-col",
        "items-center",
        "gap-3",
        "pb-4",
        "bg-[#0a0f1f]",
        "max-w-7xl",
        "mx-auto",
        "px-4",
        "py-4",
        "justify-between",
        "items-center",
        "bg-[#0a0f1f]",
        "shadow-lg",
        "z-10",
        "ml-auto"
    ],
    plugins: [require("daisyui")],
    daisyui: {
        themes: [
            {
                light: {
                    primary: "#0b092c",
                    primaryContent: "#082f0c",

                    secondary: "#d1d5db",
                    accent: "#9333ea",
                    neutral: "#1f2937",
                    "base-100": "#a1d4eb",
                    "info": "#2563eb",
                    "success": "#082516",
                    "warning": "#ca8a04",
                    "error": "#dc2626",
                },
                dark: {
                    primary: "#22d3ee",
                    secondary: "#64748b",
                    accent: "#8b5cf6",
                    neutral: "#6d8279",
                    "base-100": "#0f172a",
                    "info": "#0ca5e9",
                    "success": "#2dd4bf",
                    "warning": "#facc15",
                    "error": "#f87171",
                },
            },
        ],
    },
};
